var club = {
    경기고:{
        name: '경기고등학교',
        field: '고등학교',
        place: '643',
        address: '서울특별시 강남구 삼성1동 영동대로',
        src: 'images/twice.jpg',
        hook: '자유인 문화인 평화인을 기르는 학교',
        phone: '02-3496-7300',
        web: 'http://www.kyunggi.hs.kr/index.do',
        fb: 'https://www.facebook.com/kyunggihsdaejeon',
        icon: 'school',
        lat: 37.517068,
        lng: 127.056214,
        floor: 1,
        zoom: 18
    },
    학생동:{
        name: '학생동',
        field: '학교',
        place: '',
        address: '보건실, 연수협력실 등',
        src: 'images/twice.jpg',
        hook: '보건실, 연수협력실 등',
        phone: '02-3496-7300',
        web: 'http://www.kyunggi.hs.kr/index.do',
        fb: 'https://www.facebook.com/kyunggihsdaejeon',
        icon: 'business',
        lat: 37.517068,
        lng: 127.056214,
        floor: 1,
        zoom: 18
    },
    관리동:{
        name: '관리동',
        field: '학교',
        place: '',
        address: '행정실, 방송실, 교장실 등',
        hook: '행정실, 방송실, 교장실 등',
        phone: '02-3496-7300',
        web: 'http://www.kyunggi.hs.kr/index.do',
        fb: 'https://www.facebook.com/kyunggihsdaejeon',
        icon: 'business',
        lat: 37.517068,
        lng: 127.056214,
        floor: 1,
        zoom: 18
    },
    화동관:{
        name: '화동관',
        field: '학교',
        place: '',
        address: '멀티미디어실, 생활지도부 등',
        hook: '멀티미디어실, 생활지도부 등',
        phone: '02-3496-7300',
        web: 'http://www.kyunggi.hs.kr/index.do',
        fb: 'https://www.facebook.com/kyunggihsdaejeon',
        icon: 'business',
        lat: 37.517068,
        lng: 127.056214,
        floor: 1,
        zoom: 18
    },
    과학동:{
        name: '과학동',
        field: '학교',
        place: '',
        address: '실험실, 리소스룸 등',
        hook: '실험실, 리소스룸 등',
        phone: '02-3496-7300',
        web: 'http://www.kyunggi.hs.kr/index.do',
        fb: 'https://www.facebook.com/kyunggihsdaejeon',
        icon: 'business',
        lat: 37.517068,
        lng: 127.056214,
        floor: 2,
        zoom: 18
    },
    문화관:{
        name: '문화관',
        field: '학교',
        place: '',
        address: '대강당, 매점 등',
        hook: '대강당, 매점 등',
        phone: '02-3496-7300',
        web: 'http://www.kyunggi.hs.kr/index.do',
        fb: 'https://www.facebook.com/kyunggihsdaejeon',
        icon: 'business',
        lat: 37.517068,
        lng: 127.056214,
        floor: 1,
        zoom: 18
    },
    도서관:{
        name: '도서관',
        field: '학교',
        place: '',
        address: '도서관, 야자실 등',
        hook: '도서관, 야자실 등',
        phone: '02-3496-7300',
        web: 'http://www.kyunggi.hs.kr/index.do',
        fb: 'https://www.facebook.com/kyunggihsdaejeon',
        icon: 'local_library',
        lat: 37.517068,
        lng: 127.056214,
        floor: 1,
        zoom: 18
    },
    백주년:{
        name: '100주년 기념관',
        field: '학교',
        place: '',
        address: '동문회 사무실 등',
        hook: '동문회 사무실 등',
        phone: '02-3496-7300',
        web: 'http://www.kyunggi.hs.kr/index.do',
        fb: 'https://www.facebook.com/kyunggihsdaejeon',
        icon: 'account_balance',
        lat: 37.517068,
        lng: 127.056214,
        floor: 1,
        zoom: 18
    },
    체육관:{
        name: '체육관',
        field: '학교',
        place: '',
        address: '체육관, 급식실 등',
        hook: '체육관, 급식실 등',
        phone: '02-3496-7300',
        web: 'http://www.kyunggi.hs.kr/index.do',
        fb: 'https://www.facebook.com/kyunggihsdaejeon',
        icon: 'business',
        lat: 37.517068,
        lng: 127.056214,
        floor: 2,
        zoom: 18
    },
    과학기: {
        name: '과학기술정보통신부(LIST)',
        field: '이공계동아리',
        place: '2학년 13반',
        address: '학생동 4층 중앙',
        src: 'images/twice.jpg',
        hook: '\'대한민국 정보통신기술의 미래\'',
        phone: '',
        web: 'http://kglist.cf',
        fb: '',
        icon: 'memory',
        info1: 'Lorem ipsum dolor sit amet',
        info2: 'consectetur adipiscing elit',
        info3: 'Nulla hendrerit a tellus eget tincidunt',
        info4: 'Cras sit amet nulla vel odio',
        info5: 'viverra malesuada',
        lat: 37.517068,
        lng: 127.056214,
        floor: 4,
        zoom: 19
    },
    화학부: {
        name: '화학부',
        field: '이공계동아리',
        place: '화학실',
        address: '과학동 3층 중앙',
        src: 'images/',
        hook: '경기고의 전통있는 화학부! 이번엔 올리브영 컨셉으로 찾아왔습니다 많이 와주세요♡',
        phone: '01077069362',
        web: '',
        fb: 'https://www.facebook.com/kyunggichemistry/',
        icon: 'filter_tilt_shift',
        info1: '화학부의 모든 부스는 무료입니다!',
        info2: '아이스크림, 우주아이스티 등 더위를 날려버릴 먹거리부스!',
        info3: '남학생들의 시선을 끌 수 있는 향을 가진 향수!',
        info4: '시원한 향이 퍼질것 같은 바다캔들!',
        info5: '오늘 밤에 푹 쉬면서 쓰실 배스볼까지!',
        lat: 37.517068,
        lng: 127.056214,
        floor: 3,
        zoom: 19
    },
    학생회: {
        name: '학생회',
        field: '학생회',
        place: '야외 부스',
        address: '',
        src: 'images/',
        hook: '',
        phone: '',
        web: '',
        fb: '',
        icon: 'supervised_user_circle',
        info1: '',
        info2: '',
        info3: '',
        info4: '',
        info5: '',
        lat: 37.517068,
        lng: 127.056214,
        floor: 3,
        zoom: 19
    },
    실용음: {
        name: '실용음악부(홍련)',
        field: '예체능동아리',
        place: '1학년 1반',
        address: '',
        src: 'images/',
        hook: '경기고 최고 훈남들 집합소',
        phone: '01034507816',
        web: '',
        fb: 'https://www.facebook.com/hongryun/',
        icon: 'audiotrack',
        info1: '엄청난 노래실력과 연주실력으로 반하게 해드려요',
        info2: '관객들이 참여하는 공연이기에 재미도 보장해요',
        info3: '저희 부스 오시면 이게 여름인가 싶을정도로 시원해요 더위 식히고 노래도 듣고 가세요',
        info4: '오시면 준비된 음료랑 간식도 드실 수 있어요',
        info5: '기다리고 있을게요♡',
        lat: 37.517068,
        lng: 127.056214,
        floor: 0,
        zoom: 19
    },
    영어토: {
        name: '영어토론부(OAK)',
        field: '인문사회동아리',
        place: '1학년 2반',
        address: '',
        src: 'images/',
        hook: '',
        phone: '',
        web: '',
        fb: '',
        icon: 'text_format',
        info1: '',
        info2: '',
        info3: '',
        info4: '',
        info5: '',
        lat: 37.517068,
        lng: 127.056214,
        floor: 0,
        zoom: 19
    },
    미술부: {
        name: '미술부(AC7)',
        field: '예체능동아리',
        place: '1학년 3반',
        address: '',
        src: 'images/',
        hook: '',
        phone: '',
        web: '',
        fb: '',
        icon: 'color_lens',
        info1: '',
        info2: '',
        info3: '',
        info4: '',
        info5: '',
        lat: 37.517068,
        lng: 127.056214,
        floor: 0,
        zoom: 19
    },
    농구부: {
        name: '농구부',
        field: '예체능동아리',
        place: '1학년 4반',
        address: '',
        src: 'images/',
        hook: '',
        phone: '',
        web: '',
        fb: '',
        icon: 'directions_run',
        info1: '',
        info2: '',
        info3: '',
        info4: '',
        info5: '',
        lat: 37.517068,
        lng: 127.056214,
        floor: 0,
        zoom: 19
    },
    EDM: {
        name: 'EDM부',
        field: '예체능동아리',
        place: '1학년 5반',
        address: '',
        src: 'images/',
        hook: '',
        phone: '',
        web: '',
        fb: '',
        icon: 'audiotrack',
        info1: '',
        info2: '',
        info3: '',
        info4: '',
        info5: '',
        lat: 37.517068,
        lng: 127.056214,
        floor: 0,
        zoom: 19
    },
    매드스: {
        name: '매드스텝(힙합댄스부)',
        field: '예체능동아리',
        place: '1학년 6반',
        address: '',
        src: 'images/',
        hook: '',
        phone: '',
        web: '',
        fb: '',
        icon: 'audiotrack',
        info1: '',
        info2: '',
        info3: '',
        info4: '',
        info5: '',
        lat: 37.517068,
        lng: 127.056214,
        floor: 0,
        zoom: 19
    },
    신문부: {
        name: '신문부',
        field: '인문사회동아리',
        place: '1학년 7반',
        address: '',
        src: 'images/',
        hook: '',
        phone: '',
        web: '',
        fb: '',
        icon: 'chrome_reader_mode',
        info1: '',
        info2: '',
        info3: '',
        info4: '',
        info5: '',
        lat: 37.517068,
        lng: 127.056214,
        floor: 0,
        zoom: 19
    },
    심리부: {
        name: '심리부',
        field: '인문사회동아리',
        place: '1학년 8반',
        address: '',
        src: 'images/',
        hook: '',
        phone: '',
        web: '',
        fb: '',
        icon: 'favorite_border',
        info1: '',
        info2: '',
        info3: '',
        info4: '',
        info5: '',
        lat: 37.517068,
        lng: 127.056214,
        floor: 0,
        zoom: 19
    },
    항공부: {
        name: '항공부(KAST)',
        field: '이공계동아리',
        place: '1학년 9반',
        address: '',
        src: 'images/',
        hook: '제4차산업혁명의 선두주자, 다양한 드론체험',
        phone: '',
        web: '',
        fb: 'https://www.facebook.com/KyunggiAvitaionScienceTeam/',
        icon: 'flight',
        info1: 'Sphero를 이용한 미로 탈출 타임 어택',
        info2: 'Parrot Mambo를 이용한 드론 비행 체험',
        info3: 'RC카 드론을 이용하여 RC카 주행 및 드론 비행 체험',
        info4: '삼성 VR 기어를 이용한 3차원 시각 체험',
        info5: '4종류의 미니게임(항공 관련 OX 퀴즈, 항공 다트, 항공 스피드 퀴즈, 비행기 모형 알까기)',
        lat: 37.517068,
        lng: 127.056214,
        floor: 0,
        zoom: 19
    },
    교지편: {
        name: '교지편집부',
        field: '인문사회동아리',
        place: '1학년 10반',
        address: '',
        src: 'images/',
        hook: '',
        phone: '',
        web: '',
        fb: '',
        icon: 'chrome_reader_mode',
        info1: '',
        info2: '',
        info3: '',
        info4: '',
        info5: '',
        lat: 37.517068,
        lng: 127.056214,
        floor: 0,
        zoom: 19
    },
    헬스부: {
        name: '헬스부',
        field: '예체능동아리',
        place: '1학년 11반',
        address: '',
        src: 'images/',
        hook: '',
        phone: '',
        web: '',
        fb: '',
        icon: 'fitness_center',
        info1: '',
        info2: '',
        info3: '',
        info4: '',
        info5: '',
        lat: 37.517068,
        lng: 127.056214,
        floor: 0,
        zoom: 19
    },
    창의수: {
        name: '창의수학탐구부',
        field: '이공계동아리',
        place: '1학년 12반',
        address: '',
        src: 'images/',
        hook: '',
        phone: '',
        web: '',
        fb: '',
        icon: 'functions',
        info1: '',
        info2: '',
        info3: '',
        info4: '',
        info5: '',
        lat: 37.517068,
        lng: 127.056214,
        floor: 0,
        zoom: 19
    },
    아이스: {
        name: '아이스하키부',
        field: '예체능동아리',
        place: '1학년 13반',
        address: '',
        src: 'images/',
        hook: '',
        phone: '',
        web: '',
        fb: '',
        icon: 'directions_run',
        info1: '',
        info2: '',
        info3: '',
        info4: '',
        info5: '',
        lat: 37.517068,
        lng: 127.056214,
        floor: 0,
        zoom: 19
    },
    경제부: {
        name: '경제부(KLX)',
        field: '인문사회동아리',
        place: '1학년 14반',
        address: '',
        src: 'images/',
        hook: '화동제 스타트는 경제부에서. 폴라로이드 사진 찍고 물풍선 던지자☆',
        phone: '01075583393',
        web: '',
        fb: '',
        icon: 'trending_up',
        info1: '같이 온 친구들이랑 폴라로이드 사진 찍자!',
        info2: '경기고 등산 수고 했어! 꿀잼 인간과녁 물풍선 던지기',
        info3: '경제 스피드 퀴즈 맞추고 상품까지!',
        info4: '모든 체험 완료시 슬러쉬!',
        info5: '경기고 얼굴간판 경제부(KLX) 화동제 메인 1층 동아리! 많이 와주세요!',
        lat: 37.517068,
        lng: 127.056214,
        floor: 0,
        zoom: 19
    },
    유네스: {
        name: '유네스코부',
        field: '인문사회동아리',
        place: '2학년 1반',
        address: '',
        src: 'images/',
        hook: '',
        phone: '',
        web: '',
        fb: '',
        icon: 'text_format',
        info1: '',
        info2: '',
        info3: '',
        info4: '',
        info5: '',
        lat: 37.517068,
        lng: 127.056214,
        floor: 0,
        zoom: 19
    },
    네셔널: {
        name: '네셔널트러스트부',
        field: '인문사회동아리',
        place: '2학년 2반',
        address: '',
        src: 'images/',
        hook: '',
        phone: '',
        web: '',
        fb: '',
        icon: 'language',
        info1: '',
        info2: '',
        info3: '',
        info4: '',
        info5: '',
        lat: 37.517068,
        lng: 127.056214,
        floor: 0,
        zoom: 19
    },
    컴퓨터: {
        name: '컴퓨터부(CE-L)',
        field: '이공계동아리',
        place: '2학년 3반',
        address: '',
        src: 'images/',
        hook: '당신의 마음을 해킹합니다!컴퓨터와 IT분야에 관심이 많은 학생들이 모인 동아리',
        phone: '01051001566',
        web: '',
        fb: '',
        icon: 'desktop_windows',
        info1: 'VR을 이용한 롤러코스터 체험 및 다양한 게임을 플레이 해보세요!',
        info2: '테블릿으로 직접 그림을 그린 후 즉석으로 인화해서 작품을 가져가실 수 있게 해드립니다.',
        info3: '랜덤추첨을 통해 당첨되신 분들에게 일러스트를 그려드립니다!',
        info4: '이외에도 다양한 즐길거리가 준비되어 있습니다.',
        info5: '무더운 여름 갈증과 지친 몸을 달래줄 시원한 음료와 간식들이 준비되어 있습니다.',
        lat: 37.517068,
        lng: 127.056214,
        floor: 0,
        zoom: 19
    },
    기계공: {
        name: '기계공학부',
        field: '이공계동아리',
        place: '2학년 4반',
        address: '',
        src: 'images/',
        hook: '',
        phone: '',
        web: '',
        fb: '',
        icon: 'build',
        info1: '',
        info2: '',
        info3: '',
        info4: '',
        info5: '',
        lat: 37.517068,
        lng: 127.056214,
        floor: 0,
        zoom: 19
    },
    천문학: {
        name: '천문학부',
        field: '이공계동아리',
        place: '2학년 5반',
        address: '',
        src: 'images/',
        hook: '',
        phone: '',
        web: '',
        fb: 'https://www.facebook.com/%EA%B2%BD%EA%B8%B0%EA%B3%A0%EB%93%B1%ED%95%99%EA%B5%90-%EC%B2%9C%EB%AC%B8%ED%95%99%EB%B6%80-KAC-1809846772650085/',
        icon: 'star_border',
        info1: '',
        info2: '',
        info3: '',
        info4: '',
        info5: '',
        lat: 37.517068,
        lng: 127.056214,
        floor: 0,
        zoom: 19
    },
    영자신: {
        name: '영자신문부(KyunggiYouth)',
        field: '인문사회동아리',
        place: '2학년 6반',
        address: '',
        src: 'images/',
        hook: '',
        phone: '',
        web: '',
        fb: '',
        icon: 'chrome_reader_mode',
        info1: '',
        info2: '',
        info3: '',
        info4: '',
        info5: '',
        lat: 37.517068,
        lng: 127.056214,
        floor: 0,
        zoom: 19
    },
    청담농: {
        name: '청담농사부',
        field: '인문사회동아리',
        place: '2학년 7반',
        address: '',
        src: 'images/',
        hook: '',
        phone: '',
        web: '',
        fb: '',
        icon: 'local_florist',
        info1: '',
        info2: '',
        info3: '',
        info4: '',
        info5: '',
        lat: 37.517068,
        lng: 127.056214,
        floor: 0,
        zoom: 19
    },
    배구부: {
        name: '배구부',
        field: '예체능동아리',
        place: '2학년 8반',
        address: '',
        src: 'images/',
        hook: '',
        phone: '',
        web: '',
        fb: '',
        icon: 'directions_run',
        info1: '',
        info2: '',
        info3: '',
        info4: '',
        info5: '',
        lat: 37.517068,
        lng: 127.056214,
        floor: 0,
        zoom: 19
    },
    경영부: {
        name: '경영부',
        field: '인문사회동아리',
        place: '2학년 9반',
        address: '',
        src: 'images/',
        hook: '',
        phone: '',
        web: '',
        fb: '',
        icon: 'attach_money',
        info1: '',
        info2: '',
        info3: '',
        info4: '',
        info5: '',
        lat: 37.517068,
        lng: 127.056214,
        floor: 0,
        zoom: 19
    },
    축구부: {
        name: '축구부',
        field: '예체능동아리',
        place: '2학년 10반',
        address: '',
        src: 'images/',
        hook: '',
        phone: '',
        web: '',
        fb: '',
        icon: 'directions_run',
        info1: '',
        info2: '',
        info3: '',
        info4: '',
        info5: '',
        lat: 37.517068,
        lng: 127.056214,
        floor: 0,
        zoom: 19
    },
    도서부: {
        name: '도서부(Papyrus)',
        field: '인문사회동아리',
        place: '2학년 11반',
        address: '',
        src: 'images/',
        hook: '',
        phone: '',
        web: '',
        fb: '',
        icon: 'book',
        info1: '',
        info2: '',
        info3: '',
        info4: '',
        info5: '',
        lat: 37.517068,
        lng: 127.056214,
        floor: 0,
        zoom: 19
    },
    수학부: {
        name: '수학부(KMOC)',
        field: '이공계동아리',
        place: '2학년 12반',
        address: '',
        src: 'images/',
        hook: '',
        phone: '',
        web: '',
        fb: '',
        icon: 'functions',
        info1: '',
        info2: '',
        info3: '',
        info4: '',
        info5: '',
        lat: 37.517068,
        lng: 127.056214,
        floor: 0,
        zoom: 19
    },
    검도부: {
        name: '검도부',
        field: '예체능동아리',
        place: '검도실',
        address: '',
        src: 'images/',
        hook: '',
        phone: '',
        web: '',
        fb: '',
        icon: 'colorize',
        info1: '',
        info2: '',
        info3: '',
        info4: '',
        info5: '',
        lat: 37.517068,
        lng: 127.056214,
        floor: 0,
        zoom: 19
    },
    힙합음: {
        name: '힙합음악부(Absolute)',
        field: '예체능동아리',
        place: '(경기인의 밤)',
        address: '체육관',
        src: 'images/',
        hook: '',
        phone: '',
        web: '',
        fb: '',
        icon: 'music_note',
        info1: '',
        info2: '',
        info3: '',
        info4: '',
        info5: '',
        lat: 37.517068,
        lng: 127.056214,
        floor: 0,
        zoom: 19
    },
    연극부: {
        name: '연극부',
        field: '예체능동아리',
        place: '멀티미디어실',
        address: '',
        src: 'images/',
        hook: '연극 “우리읍내” 작품을 공연합니다.',
        phone: '01028995494',
        web: '',
        fb: '',
        icon: 'people',
        info1: '잘생긴 배우들이 연기하는 유쾌하고 재밌는 작품',
        info2: '무더운 더위를 시원하게 날려줄 에어컨과 함께 편히 앉아서 볼 수 있는 연극',
        info3: '믿고보는 작년 최우수 동아리 작품',
        info4: '여자배우들이 도와줘 완성도가 더욱 돋보이는 작품',
        info5: '이거 보고있는 예쁜언니 놀러와♡',
        lat: 37.517068,
        lng: 127.056214,
        floor: 0,
        zoom: 19
    },
    오케스: {
        name: '오케스트라부',
        field: '예체능동아리',
        place: '대강당',
        address: '문화관',
        src: 'images/',
        hook: '경기오케스트라',
        phone: '01063726145',
        web: '',
        fb: '',
        icon: 'music_note',
        info1: '경기고에서 가장 시원한 곳(에어컨 4개의 위력!)',
        info2: '500석의 넓은 강당',
        info3: '경기고 대 선배님들과의 협연',
        info4: '더울 때  와서 음악도 듣기 좋은 동아리 ',
        info5: '경기고 후문 문화관 1층 !',
        lat: 37.517068,
        lng: 127.056214,
        floor: 0,
        zoom: 19
    },
    물리부: {
        name: '물리부',
        field: '이공계동아리',
        place: '물리실',
        address: '',
        src: 'images/',
        hook: '작년 축제1등! 믿고오세요 ㅎㅎ',
        phone: '01020003756',
        web: '',
        fb: 'https://www.facebook.com/%EA%B2%BD%EA%B8%B0%EA%B3%A0%EB%93%B1%ED%95%99%EA%B5%90-%EB%AC%BC%EB%A6%AC%EB%B36%80-Phronesis-1788663611457619/',
        icon: 'explore',
        info1: '개',
        info2: '꿀',
        info3: '잼',
        lat: 37.517068,
        lng: 127.056214,
        floor: 0,
        zoom: 19
    },
    방송부: {
        name: '방송부',
        field: '인문사회동아리',
        place: '방송실',
        address: '',
        src: 'images/',
        hook: '잘생긴애 옆에 잘생긴애 옆에 잘생긴애 옆에 잘생긴애',
        phone: '01022215707',
        web: '',
        fb: 'https://www.facebook.com/%EA%B2%BD%EA%B8%B0%EA%B3%A0-%EB%B0%A9%EC%86%A1%EB%B6%80-KHBS-1564662743861886/',
        icon: 'mic',
        info1: '부원들이 잘생김',
        info2: '부원들이 진짜 잘생김',
        info3: '부원들이 다 잘생김 ',
        info4: '동아리들 중에 젤 잘생김',
        info5: '특징 5개로 못 담을 정도로 잘생김',
        lat: 37.517068,
        lng: 127.056214,
        floor: 0,
        zoom: 19
    },
    생물부: {
        name: '생물부(KBRC)',
        field: '이공계동아리',
        place: '생물실',
        address: '',
        src: 'images/',
        hook: '',
        phone: '',
        web: '',
        fb: '',
        icon: 'terrain',
        info1: '',
        info2: '',
        info3: '',
        info4: '',
        info5: '',
        lat: 37.517068,
        lng: 127.056214,
        floor: 0,
        zoom: 19
    },
    창의융: {
        name: '창의융합과학부(CSS)',
        field: '이공계동아리',
        place: '지학실',
        address: '',
        src: 'images/',
        hook: '우리같이 융합하자',
        phone: '',
        web: '',
        fb: '',
        icon: 'whatshot',
        info1: '',
        info2: '',
        info3: '',
        info4: '',
        info5: '',
        lat: 37.517068,
        lng: 127.056214,
        floor: 0,
        zoom: 19
    },
}

var place = []
var index = [];
for (var i in club) {
    index.push(i);
    place.push(club[i].name);
}