var club = {
    과학기: {
        name: '과학기술정보통신부(LIST)',
        field: '이공계',
        place: '2학년 13반',
        address: '학생동 4층 중앙',
        src: 'images/',
        hook: '대한민국 정보통신기술의 미래',
        info1: '',
        info2: '',
        info3: '',
        info4: '',
        info5: '',
    },
    화학부: {
        name: '화학부s',
        field: '이공계',
        place: '2학년 13반',
        address: '학생동 4층 중앙',
        src: 'images/',
        hook: '대한민국 정보통신기술의 미래',
        info1: '',
        info2: '',
        info3: '',
        info4: '',
        info5: '',
    },
}